spring:
  profiles:
    active: local
cub:
  spring:
    kafka:
      bootstrap-servers: localhost:9092
      topic:
        batch:
          request: batchRequests
          reply: batchReplies
        query:
          request: queryRequests
          reply: querykReplies
      consumer:
          group-id: consumerGroupId
          reply:
            group-id: repliesGroupId
server:
  port: 8090
