spring:
  profiles:
    active: local
cub:
  spring:
    kafka:
      bootstrap-servers: localhost:9092
      batch:
        topic:
          request: batchRequests
          reply: batchReplies
        consumer:
          group-id: batchConsumerGroupId
        producer:
          prefix: batch_
      query:
        topic:
        consumer:
          group-id: queryConsumerGroupId
          reply:
            group-id: queryRepliesGroupId
server:
  port: 8080
